import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# ==========================================
# Configuration Parameters
# ==========================================
CSV_FILENAME = "rod_temp_data_skip80.csv"
GIF_FILENAME = "heat_evolution.gif"

# Control the animation speed and size
FPS = 10                    # Frames per second for the final GIF
FRAME_SKIP = 10             # Number of rows to skip between frames (useful if you have 2000+ rows)
ANIMATION_DURATION_SEC = 10  # Alternative: Calculate required FPS based on duration

# ==========================================
# 1. Load the Data
# ==========================================
print(f"Loading data from {CSV_FILENAME}...")
# np.loadtxt easily handles the comma-separated rows generated by your CUDA code
data = np.loadtxt(CSV_FILENAME, delimiter=",")

num_time_steps = data.shape[0]
num_spatial_points = data.shape[1]

print(f"Loaded {num_time_steps} time steps across {num_spatial_points} spatial points.")

# Apply frame skipping to make rendering faster and the GIF smaller
frames_to_render = np.arange(0, num_time_steps, FRAME_SKIP)

# ==========================================
# 2. Setup the Plot Canvas
# ==========================================
fig, ax = plt.subplots(figsize=(10, 6))

# Define the physical space (x-axis)
x = np.arange(num_spatial_points)

# Create an empty line object that we will update in the animation loop
line, = ax.plot(x, data[0, :], color='red', linewidth=2)

# Set static axes limits so the plot doesn't jump around
ax.set_xlim(0, num_spatial_points - 1)
# Padding the Y-axis slightly beyond the min/max of the entire dataset
ax.set_ylim(np.min(data) - 10, np.max(data) + 10)

ax.set_title("1D Heat Equation Evolution")
ax.set_xlabel("Spatial Points (Skipped by 80)")
ax.set_ylabel("Temperature")
ax.grid(True, linestyle='--', alpha=0.6)

# Text object to display the current time step on the plot
time_text = ax.text(0.02, 0.95, '', transform=ax.transAxes)

# ==========================================
# 3. The Animation Logic
# ==========================================
def update(frame_idx):
    """
    This function is called for each frame. 
    It updates the Y-data of the line and the text counter.
    """
    current_temp_profile = data[frame_idx, :]
    line.set_ydata(current_temp_profile)
    time_text.set_text(f'Time Step (Row): {frame_idx}')
    
    return line, time_text

print("Generating animation...")
# Create the animation object
ani = animation.FuncAnimation(
    fig, 
    update, 
    frames=frames_to_render, 
    blit=True,              # Blit=True optimizes rendering by only redrawing changing parts
    interval=1000 / FPS     # Interval is in milliseconds between frames
)

# ==========================================
# 4. Save the GIF
# ==========================================
print(f"Saving to {GIF_FILENAME} at {FPS} FPS...")
# Pillow is built into modern matplotlib for GIF saving, no external tools required
writer = animation.PillowWriter(fps=FPS)
ani.save(GIF_FILENAME, writer=writer)

print("Done! GIF saved successfully.")
plt.close()